import Head from "next/head";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";
import Viz from "../components/Viz";
import React from "react";
import ComputerIcon from "@mui/icons-material/Computer";
import QueryStatsIcon from "@mui/icons-material/QueryStats";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import EmailIcon from "@mui/icons-material/Email";
import GitHubIcon from "@mui/icons-material/GitHub";

import Projects from "../components/Projects";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Michael Bergerson | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* Open Graph */}
        <meta
          property="og:url"
          content="https://www.michaelbergerson.com/"
          key="ogurl"
        />
        <meta
          property="og:image"
          content={"https://www.michaelbergerson.com/images/Portfolio.png"}
          key="ogimage"
        />
        <meta
          property="og:site_name"
          content="michaelbergerson.com"
          key="ogsitename"
        />
        <meta
          property="og:title"
          content="Portfolio | michealbergerson.com"
          key="ogtitle"
        />
        <meta
          property="og:description"
          content="Michael Bergerson's Portfolio"
          key="ogdesc"
        />

        {/* <!-- Facebook Meta Tags --> */}
        <meta property="og:url" content="https://www.michaelbergerson.com/" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Portfolio | michealbergerson.com" />
        <meta
          property="og:description"
          content="Michael Bergerson's Portfolio"
        />
        <meta
          property="og:image"
          content="https://www.michaelbergerson.com/images/Portfolio.png"
        />

        {/* <!-- Twitter Meta Tags --> */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta property="twitter:domain" content="michaelbergerson.com" />
        <meta
          property="twitter:url"
          content="https://www.michaelbergerson.com/"
        />
        <meta name="twitter:title" content="Portfolio | michealbergerson.com" />
        <meta
          name="twitter:description"
          content="Michael Bergerson's Portfolio"
        />
        <meta
          name="twitter:image"
          content="https://www.michaelbergerson.com/images/Portfolio.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section id="hero" className={styles.heroContainer}>
          <div className={styles.heroTextContainer}>
            <div className={styles.heroTextGroup}>
              <div className={styles.heroText}>
                Hi, I am{" "}
                <span className={styles.spanColor}>Michael Bergerson</span>,
              </div>
              <div className={styles.heroSubText}>
                Data Analyst / Web Developer
              </div>
              <div className={styles.heroButtonDiv}>
                <Button
                  size="large"
                  href="#contact"
                  variant="outlined"
                  className={`${styles.buttonFont} ${styles.heroButton}`}
                  sx={{
                    marginTop: "2rem",
                    borderWidth: "0.5rem",
                    fontWeight: "bold",
                    color: "#fff",
                    borderColor: "#7ed957",
                    ":hover": {
                      borderColor: "white",
                      color: "#7ed957",
                      borderWidth: "0.5rem",
                    },
                  }}
                >
                  Contact Me
                </Button>
              </div>
            </div>
          </div>
          <Viz />
        </section>

        <section id="about" className={styles.aboutContainer}>
          <div className={styles.sectionHeader}>Who am I?</div>
          <div className={styles.bgDiv}>
            <div className={styles.aboutDiv}>
              <p className={`${styles.buttonFont} ${styles.aboutText}`}>
                My name is Michael Bergerson, I graduated from Oregon State
                University with a Bachelors of Science in Economics. My skill
                set is a unique mix between data science and web development. I
                can clean, visualize, manipulate, and explore data. While also
                building frontends and backends for the web. I was pursuing data
                analytics when I then picked up web development while learning
                data visualization libraries. Whether it is purely data
                analytics, web development or both. I can apply my knowledge and
                determination to help solve your problems.
              </p>
            </div>
          </div>
        </section>
        <section id="skills" className={styles.aboutContainer}>
          <div className={styles.sectionHeader}>Skills</div>
          <div className={styles.bgDiv}>
            <div className={styles.skillsDiv}>
              <div className={styles.dataDiv}>
                <div className={styles.dataIconDiv}>
                  <QueryStatsIcon
                    sx={{ fontSize: "3rem" }}
                    className={styles.dataIcon}
                  />
                </div>
                <h3
                  className={`${styles.buttonFont}`}
                  style={{ textAlign: "center" }}
                >
                  Data Science
                </h3>
                <p
                  className={`${styles.buttonFont}`}
                  style={{ textAlign: "center" }}
                >
                  <strong>Languages:</strong>Python, R, SQL, Javascript,
                  Typescript, CSS HTML
                </p>
                <p
                  className={`${styles.buttonFont}`}
                  style={{ textAlign: "center" }}
                >
                  <strong>Technologies:</strong> Tableau, Pandas, NumPy,
                  Tidyverse, Excel, Google Sheets, Plotly, Seaborn, ggplot2,
                  Statistics, Jupyter Notebook, BigQuery, APIs, React, D3.js,
                  Node.js, PostgreSQL, Git
                </p>
              </div>
              <div className={styles.dataDiv}>
                <div className={styles.webIconDiv}>
                  <ComputerIcon
                    sx={{ fontSize: "3rem" }}
                    className={styles.webIcon}
                  />
                </div>
                <h3
                  className={`${styles.buttonFont}`}
                  style={{ textAlign: "center" }}
                >
                  Web Developement
                </h3>
                <p
                  className={`${styles.buttonFont}`}
                  style={{ textAlign: "center" }}
                >
                  <strong>Languages:</strong>Javascript, Typescript, CSS HTML,
                  Python, R, SQL
                </p>
                <p
                  className={`${styles.buttonFont}`}
                  style={{ textAlign: "center" }}
                >
                  <strong>Technologies:</strong> React, D3.js, Plotly.js
                  Three.js, Material UI, Tailwind CSS, React Router, Formik,
                  React Table, Node.js, Next.js, Express, Redis, PostgreSQL,
                  GraphQL, Apollo Server, Argon2, Typeorm, Stripe, Git, Tableau,
                  Pandas, Tidyverse, Plotly
                </p>
              </div>
            </div>
          </div>
        </section>
        <section id="projects" className={styles.aboutContainer}>
          <div className={styles.sectionHeader}>Projects</div>
          <div className={styles.bgDiv}>
            <Projects />
          </div>
        </section>
        <section id="contact" className={styles.aboutContainer}>
          <div className={styles.sectionHeader}></div>
          <div style={{ display: "grid", placeContent: "center" }}>
            <div className={styles.contactDiv}>
              <Button href="https://www.linkedin.com/in/michaelbergerson">
                <LinkedInIcon
                  sx={{ fontSize: "4rem" }}
                  className={styles.contactIcons}
                />
              </Button>
              <Button href="https://github.com/anxietyattacked">
                <GitHubIcon
                  className={styles.contactIcons}
                  sx={{ fontSize: "4rem" }}
                />
              </Button>
              <Button href="mailto:michaelbergerson@gmail.com">
                <EmailIcon
                  sx={{ fontSize: "4rem" }}
                  className={styles.contactIcons}
                />
              </Button>
            </div>
            <h6 className={`${styles.buttonFont}  ${styles.contactText}`}>
              Email: michaelbergerson@gmail.com
            </h6>
          </div>
        </section>
      </main>
      <footer className={styles.footer}>Michael Bergerson © 2022</footer>
    </div>
  );
}
